import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";

const src = (file) => readFileSync(path.join(process.cwd(), file), "utf8");
const nav = src("src/features/portal/ResponsivePrimaryNav.tsx");
const shell = src("src/components/AppShell.tsx");
const returnIntent = src("src/features/portal/returnIntent.ts");
const home = src("src/features/portal/PublicHomeView.tsx");
const claw = src("src/features/portal/PublicClawPreview.tsx");
const track = src("src/features/portal/PublicTrackRecordView.tsx");
const portalApi = src("src/features/portal/publicPortalApi.ts");

assert.match(nav, /desktopPrimaryItems/);
assert.match(nav, /aria-current/);
assert.match(nav, /onNavigate\("home"\)/);
assert.match(shell, /saveReturnIntent/);
assert.match(shell, /createRouteReturnIntent\(nextView, selectedSymbol\)/);
assert.match(shell, /restoreReturnIntent/);
assert.match(shell, /setValueClawSignalContext\(restoration\.signal\)/);
assert.match(shell, /ResponsivePrimaryNav/);
assert.match(returnIntent, /consumeReturnIntent/);
assert.match(home, /体验公开雷达/);
assert.match(home, /策略引擎/);
assert.match(home, /AI Claw/);
assert.match(home, /查看历史战绩/);
assert.doesNotMatch(home, /胜率\s*80|平均收益\s*65/);
assert.match(claw, /示例问题/);
assert.match(claw, /登录后使用 AI Claw/);
assert.doesNotMatch(claw, /apiPost|fetch\(/);
assert.match(shell, /verifiedIdentity\s*\?\s*<ValueClawPage/);
assert.match(shell, /<RadarPage authenticated=\{verifiedIdentity\}/);
assert.doesNotMatch(shell, /<RadarPage authenticated=\{currentUserVerificationReady && currentUserVerified && Boolean\(currentUser\.id\)\}/);
assert.match(shell, /<PublicClawPreview/);
assert.match(shell, /const shellView = resolvePortalShellView\(view\);[\s\S]*app-shell view-\$\{showSymbolDetail \? "symbol" : shellView\}/);
assert.match(track, /fixed-window-v1|固定窗口/);
assert.match(track, /completed24hCount/);
assert.match(track, /pending24hCount/);
assert.match(track, /会员解锁/);
assert.match(track, /数据已过期/);
assert.match(track, /重新加载/);
assert.match(track, /sessionStorage/);
assert.match(track, /getPublicSignals/);
assert.match(track, /getPublicPerformanceSummary/);
assert.match(track, /toTrackRecordRow/);
assert.match(shell, /view === "track-record"/);
assert.match(shell, /view !== "track-record" && contentView === "radar"/);
assert.match(shell, /getPublicSignals/);
assert.match(shell, /portalSignalSource/);
assert.match(shell, /portalSignalsForResult/);
assert.match(shell, /createPortalRequestCoordinator/);
assert.match(shell, /canCreateMemberOrder/);
assert.match(track, /publicTrackRecordFilterKey/);
assert.match(shell, /publicSignalResponse\?\.delayHours/);
assert.match(shell, /if \(!currentUser\.id\) return;/);
assert.match(shell, /saveReturnIntent\(window\.sessionStorage, createRouteReturnIntent\("data"/);
assert.match(portalApi, /\/api\/strategy\/public-signals/);

console.log("public portal source tests passed");
