import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";

const src = (file) => readFileSync(path.join(process.cwd(), file), "utf8");
const nav = src("src/features/portal/ResponsivePrimaryNav.tsx");
const shell = src("src/components/AppShell.tsx");
const returnIntent = src("src/features/portal/returnIntent.ts");
const home = src("src/features/portal/PublicHomeView.tsx");
const claw = src("src/features/portal/PublicClawPreview.tsx");
const track = src("src/features/portal/PublicTrackRecordView.tsx");
const trackPresentation = src("src/features/portal/TrackRecordPresentation.tsx");
const portalApi = src("src/features/portal/publicPortalApi.ts");
const metadata = src("src/features/portal/publicMetadata.ts");

assert.match(nav, /desktopPrimaryItems/);
assert.match(nav, /aria-current/);
assert.match(nav, /onNavigate\("home"\)/);
assert.match(shell, /saveReturnIntent/);
assert.match(shell, /createRouteReturnIntent\(nextView, selectedSymbol\)/);
assert.match(shell, /restoreReturnIntent/);
assert.match(shell, /setValueClawSignalContext\(restoration\.signal\)/);
assert.match(shell, /ResponsivePrimaryNav/);
assert.match(returnIntent, /consumeReturnIntent/);
assert.match(home, /体验公开雷达/);
assert.match(home, /策略引擎/);
assert.match(home, /AI Claw/);
assert.match(home, /delayHours/);
assert.doesNotMatch(home, /真实信号延迟 8 小时/);
assert.match(home, /查看历史战绩/);
assert.doesNotMatch(home, /胜率\s*80|平均收益\s*65/);
assert.match(claw, /示例问题/);
assert.match(claw, /登录后使用 AI Claw/);
assert.doesNotMatch(claw, /apiPost|fetch\(/);
assert.match(shell, /verifiedIdentity\s*\?\s*<ValueClawPage/);
assert.match(shell, /<RadarPage authenticated=\{verifiedIdentity\}/);
assert.doesNotMatch(shell, /<RadarPage authenticated=\{currentUserVerificationReady && currentUserVerified && Boolean\(currentUser\.id\)\}/);
assert.match(shell, /<PublicClawPreview/);
assert.match(shell, /const shellView = resolvePortalShellView\(view\);[\s\S]*app-shell view-\$\{showSymbolDetail \? "symbol" : shellView\}/);
assert.match(track, /数据已过期/);
assert.match(track, /重新加载/);
assert.match(track, /sessionStorage/);
assert.match(track, /getPublicSignals/);
assert.match(track, /getPublicPerformanceSummary/);
assert.match(track, /toTrackRecordRow/);
assert.match(track, /hasMore/);
assert.match(track, /nextPage/);
assert.match(track, /<TrackRecordHero/);
assert.match(track, /<TrustSummary/);
assert.match(track, /<TrustSummaryLoading\s*\/\s*>/, "initial loading must reserve the trust-summary footprint");
assert.match(track, /displayState\.kind === "loading"/, "the trust placeholder must only represent a loading summary");
assert.match(track, /<TrackRecordFilters/);
assert.match(track, /<TrackRecordList/);
assert.match(track, /<MethodologyDisclosure/);
assert.match(track, /onUnlock\(\{ symbol, direction \}\)/);
assert.match(track, /pagination\.nextPage/);
assert.match(track, /void load\(pagination\.nextPage/);
assert.doesNotMatch(track, /track-summary-grid/);
assert.doesNotMatch(track, /track-methodology">/);
assert.match(trackPresentation, /export function TrustSummary/);
assert.match(trackPresentation, /export function TrustSummaryLoading/);
assert.match(trackPresentation, /aria-busy="true"/);
assert.match(trackPresentation, /track-trust-grid[\s\S]*track-trust-primary/, "the loading summary must preserve the real summary grid structure");
assert.doesNotMatch(trackPresentation, /TrustSummaryLoading[\s\S]*?(?:0%|0 条)/, "the loading placeholder must not fabricate metrics");
assert.match(trackPresentation, /1h 方向命中率/);
assert.match(trackPresentation, /公开信号样本/);
assert.match(trackPresentation, /平均方向收益/);
assert.match(trackPresentation, /export function TrackRecordFilters/);
assert.match(trackPresentation, /aria-pressed=\{props\.direction === item\}/, "direction controls must expose their selected state");
assert.match(trackPresentation, /全部方向/);
assert.match(trackPresentation, /export function TrackRecordList/);
assert.match(trackPresentation, /最近公开信号/);
assert.match(trackPresentation, /固定窗口，不挑样本/);
assert.match(trackPresentation, /<details/);
assert.doesNotMatch(trackPresentation, /命中样本|1842|2980/);
assert.match(shell, /view === "track-record"/);
assert.match(shell, /view !== "track-record" && contentView === "radar"/);
assert.match(shell, /getPublicSignals/);
assert.match(shell, /portalSignalSource/);
assert.match(shell, /portalSignalsForResult/);
assert.match(shell, /createPortalRequestCoordinator/);
assert.match(shell, /canCreateMemberOrder/);
assert.match(track, /publicTrackRecordFilterKey/);
assert.match(track, /hasCachedSnapshot:\s*Boolean\(fallback\)/, "a successful empty cache snapshot must remain distinguishable from no cache");
assert.match(track, /displayState\.hasCachedSnapshot\s*\?\s*"数据已过期"/, "stale status must not depend on cached row count");
assert.match(track, /describeTrackRecordEmptyState\(\{[\s\S]*symbol,[\s\S]*direction,[\s\S]*delayHours,[\s\S]*historyDays/, "empty copy must include active filters and server-provided public bounds");
assert.match(shell, /publicSignalResponse\?\.delayHours/);
assert.match(shell, /if \(!currentUser\.id\) return;/);
assert.match(shell, /saveReturnIntent\(window\.sessionStorage, createRouteReturnIntent\("data"/);
assert.match(portalApi, /\/api\/strategy\/public-signals/);
assert.match(metadata, /track-record/);
assert.match(metadata, /canonical/);
assert.match(metadata, /og:title/);
assert.match(shell, /syncPublicMetadata/);
assert.match(shell, /canPayMemberOrder/);
assert.match(shell, /effectivePrivatePortalState/);
assert.match(shell, /AI Claw\s*<strong>(登录后可用|需登录)/);
assert.doesNotMatch(shell, /AI Claw 每日额度[\s\S]{0,120}signalQuota/, "Plans must not present the signal quota as an AI allowance");
assert.match(shell, /团队席位/);
assert.match(shell, /常见问题/);
assert.match(shell, /自动续费|按月计费/);
assert.doesNotMatch(home, /满足 8 小时延迟条件/);

console.log("public portal source tests passed");
